name: rangyatra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img5.jpg"
  adaptive_icon_background : "#ffffff"
  adaptive_icon_foreground : "assets/images/img5.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/colors.json
    - assets/images/